### ISSUE TITLE
Timeout for code already generated never seems to reset

### ISSUE THREAD

**Issue by louis6321** [y21/discordcaptcha#145]
If a user generates a code, the code disappears and they forget what it was before they successfully verify, the bot never seems to let them generate another code (even after waiting 30+ minutes) until the bot is restarted.

As far as I can tell, the timeout controls in the config file are only for controlling how long the messages stay visible. They don't seem to control when you're able to generate another code.

I'm using the canvas tree for faster captcha generation.

**Comment by y21** [comment]
Right, the timeouts in the config file only specify for how long the response should be visible, and the bot never clears the queue that is used to check if a user has already requested a captcha.
The `captcha` field should probably be nullable, so you can set it to `null` and it never deletes captcha messages.
It'd probably also makes sense to allow users to request another verification code if the image is deleted.

**Comment by louis6321** [comment]
I definitely want the captcha messages to be deleted after a while to keep the channel clean; I'm fine with that.
But when it's deleted users should immediately be able to request a new one.

**Comment by y21** [comment]
Yeah, that makes sense. I just pushed a fix for it (https://github.com/y21/discordcaptcha/commit/dd6784bc1aa3a36d4e7d090f59f251f2164fc893). Users should now be able to request another captcha if the previous one has expired.

**Comment by louis6321** [comment]
Thanks! In terms of installing the update do I need to do `npm i && npm i typescript -g && tsc` again?

**Comment by y21** [comment]
`git pull origin canvas` should work (assuming you used `git clone` to download this repository). Then `tsc` to recompile the source. `npm i` is not needed when updating.
I think it makes sense to provide a script for updating.

**Comment by louis6321** [comment]
Fix is working perfectly, cheers.

Nah, I downloaded the zip. Decided to keep a backup by renaming the old directory, downloading and installing again and copying the config across. Working perfectly. :)
