### ISSUE TITLE
Improvement: Delete captcha immediately upon successful verification

### ISSUE THREAD

**Issue by louis6321** [y21/discordcaptcha#146]
Rather than waiting for the timeout, the captcha should be immediately deleted if verification is successful.

**Comment by y21** [comment]
Thanks. Added in https://github.com/y21/discordcaptcha/commit/e20d873b8c2f9a5a2d9e7eb1350e98b735d14463.

**Comment by louis6321** [comment]
Thanks. Will it still delete when it hits the timeout or only if the user verifies? I still like the timeout because otherwise people type !verify and then don't finish it and the channel fills up with captchas.

**Comment by y21** [comment]
Yep, it will still delete the captcha message if it hits the timeout. (This can also be disabled by setting `captcha` to null in config.json)

**Comment by louis6321** [comment]
Working perfectly. Thanks!
