### ISSUE TITLE
Members who failed a CAPTCHA are not purged from the verification queue

### ISSUE THREAD

**Issue by joker314** [y21/discordcaptcha#21]
Moved from Discord chat. Reported by @y21.

> if you fail the captcha, you will get kicked and after rejoining, you won't be able to get a new verify code.
> Because DiscordCaptcha thinks you are still in the verification queue which confuses some people.

~~I'll work on this one.~~

**Comment by y21** [comment]
Fixed in https://github.com/y21/discordcaptcha/commit/8f962e7c9d6e7051e8f53906ba4992ede6d7deba; ID will be removed from `queries` table once they leave the server and the `guildMemberRemove` event gets emitted respectively (kicking emits that event too).
