### ISSUE TITLE
Command handler

### ISSUE THREAD

**Issue by DUFC-Liam** [y21/discordcaptcha#26]
For your main file it's pretty unclean wouldn't using a simple command handler f.e.
```js
const cmdFiles = await readdir("./commands/");
  client.logger.log(`Loading a total of ${cmdFiles.length} commands.`);
  cmdFiles.forEach(f => {
    if (!f.endsWith(".js")) return;
    const response = client.loadCommand(f);
    if (response) console.log(response);
  });
```
Credit: [AnIdiotsGuide](https://github.com/AnIdiotsGuide/guidebot/blob/master/index.js#L47)

**Comment by y21** [comment]
Thanks for your requests.
I am already working on a rewrite which included a new command handler.
