### ISSUE TITLE
Interact with data

### ISSUE THREAD

**Issue by derby1387** [y21/discordcaptcha#3]
Hey,

is it possible to interact with data, like getting an object with verifications and stuff like that? Would be cool.

**Comment by y21** [comment]
Working on it.

**Comment by y21** [comment]
[714f1fa](https://github.com/y21/discordcaptcha/commit/2fc8ac0e87573211853733550d2faa799230f93e) - Get Query
[fd22510](https://github.com/y21/discordcaptcha/commit/714f1faea346e37258121d18bcd9dfb4a9ece9f6) - Delete Query
More soon™.
