### ISSUE TITLE
Custom filenames

### ISSUE THREAD

**Issue by upgraded-adv** [y21/discordcaptcha#6]
Could you please make it that we are able to choose a custom filename, like .jpg, .jpeg and stuff

**Comment by y21** [comment]
https://github.com/y21/discordcaptcha/commit/b57706fd33442e2ae8455c863689274d216bd93e

Keep in mind that this branch is unsteady. If you don't want an unstable version and bugs, wait till it gets merged.

**Comment by upgraded-adv** [comment]
How long will it take about?

**Comment by y21** [comment]
I don't know, eta 1-7 days.
